### PR TITLE
Add new gut views

### PR DESCRIPTION
**Pull request by lingyun1010**
We have three new views for gut organ anatomogram, `gut.main.svg`, `gut.intestine.svg` and `gut.colon.svg`.

### CODE REVIEW

**Comment by sfexova** [comment]
Hi @lingyun1010 I had a look but there are a few problems - the main one being that I do not see the transition boxes to the zoom-in images, so cannot get to them in the demo (and therefore can only check gut.main now)
Screenshot 2022-09-09 at 22 05 33

This is what I've done to run the demo on my machine - is this correct? Because it looks like I am not getting the same version that we looked at together (which definitely had the transition boxes)
went to git branch feature/164401762-add-kidney-svgs
git pull
npx webpack-dev-server -d

Anyway, for the gut main that I can see, I've found the following:
gut_main:

Not seeing shape:
UBERON_0001143 hepatic vein
UBERON_0001182 superior mesenteric artery
UBERON_0001193 hepatic artery

Shouldn’t be there (and these aren’t included in my version of the svg file):
UBERON_0001155 colon
UBERON_0000160 intestine
UBERON_0005609 iliac artery

Missing from the demo list of ontology IDs:
UBERON_8410016 descending sigmoid junction - is in my version of svg
UBERON_8410000 duodeno-jejunal junction - is in my version of svg
UBERON_8410019 jejuno-ileal junction - is in my version of svg
UBERON_0035180 sigmoid artery - is in my version of svg
UBERON_0001197 ileocolic artery - is in my version of svg
UBERON_8410009 right colic artery - is in my version of svg
UBERON_0001138 superior mesenteric vein - is in my version of svg

UBERON_8410022 left colic artery - missing in my version of svg

**Comment by lingyun1010** [comment]
> Hi @lingyun1010 I had a look but there are a few problems - the main one being that I do not see the transition boxes to the zoom-in images, so cannot get to them in the demo (and therefore can only check gut.main now) Screenshot 2022-09-09 at 22 05 33
> 
> This is what I've done to run the demo on my machine - is this correct? Because it looks like I am not getting the same version that we looked at together (which definitely had the transition boxes) went to git branch feature/164401762-add-kidney-svgs git pull npx webpack-dev-server -d
> 
> Anyway, for the gut main that I can see, I've found the following: gut_main:
> 
> Not seeing shape: UBERON_0001143 hepatic vein UBERON_0001182 superior mesenteric artery UBERON_0001193 hepatic artery
> 
> Shouldn’t be there (and these aren’t included in my version of the svg file): UBERON_0001155 colon UBERON_0000160 intestine UBERON_0005609 iliac artery
> 
> Missing from the demo list of ontology IDs: UBERON_8410016 descending sigmoid junction - is in my version of svg UBERON_8410000 duodeno-jejunal junction - is in my version of svg UBERON_8410019 jejuno-ileal junction - is in my version of svg UBERON_0035180 sigmoid artery - is in my version of svg UBERON_0001197 ileocolic artery - is in my version of svg UBERON_8410009 right colic artery - is in my version of svg UBERON_0001138 superior mesenteric vein - is in my version of svg
> 
> UBERON_8410022 left colic artery - missing in my version of svg

@sfexova  It seems you are not on the right branch, please check out `feature/182999447-add-new-gut-views` instead.

**Comment by sfexova** [comment]
(ah, thanks - went to the other branch because that's where the previous anatomograms were)

I've switched to the correct branch, did npx webpack-dev-server -d but I cannot see any images at all now
Screenshot 2022-09-13 at 11 41 10

**Review by alfonsomunozpomer — APPROVED** [review]
All good.

**Pull request merged**
